name: Hugo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch submodules (Hugo themes, pandoc)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: SetupHugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: RunHugo
        run: hugo --minify

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hugo-output
          path: ./docs/
          retention-days: 1

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/
          force_orphan: true
