name: SLIDES

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, edited, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Wuppie
        run: echo "${{ GITHUB_REF }}"

      - name: Wuppie
        run: git branch

      - name: RunPandocPR
        uses: ./.github/actions/alpine-pandoc-hugo
        if: ${{ github.head_ref }}
        with:
          make-target: 'make ${{ github.head_ref }}'

      - name: RunPandocAll
        uses: ./.github/actions/alpine-pandoc-hugo
        if: ${{ ! github.head_ref }}
        with:
          make-target: 'make slides'


      - name: UploadArtefacts
        uses: actions/upload-artifact@v2
        with:
          name: slides
          path: ./pdf/
          retention-days: 1
