name: TEST
on:
  workflow_dispatch:


jobs:
  build-inside-container:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest
      options: "--entrypoint /bin/sh"
    steps:
      - run: apk --no-cache add git
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: .github/actions/alpine-pandoc-hugo/install-packages.sh
      - run: export DOCKER=false; make slides
      - uses: actions/upload-artifact@v2
        with:
          path: pdf/
          retention-days: 1

  build-using-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ./.github/actions/alpine-pandoc-hugo
        with:
          make-target: 'make slides'
      - uses: actions/upload-artifact@v2
        with:
          path: pdf/
          retention-days: 1



